import { jsPDF } from "jspdf";

export function generateReportPDF(
  report: any,
  user: any,
  type: "Daily" | "Weekly" | "Monthly",
) {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(22);
  doc.text(`${type} Report`, 105, 20, { align: "center" });

  doc.setFontSize(12);
  doc.text(`Employee: ${user.firstName} ${user.lastName}`, 20, 40);
  doc.text(`Email: ${user.email}`, 20, 47);

  if (type === "Daily") {
    doc.text(`Date: ${report.date}`, 20, 54);
  } else if (type === "Weekly") {
    doc.text(`Period: ${report.startDate} to ${report.endDate}`, 20, 54);
  } else {
    doc.text(`Month: ${report.month}/${report.year}`, 20, 54);
  }

  doc.text(`Status: ${report.status}`, 20, 61);

  doc.line(20, 65, 190, 65);

  let currentY = 75;

  // Accomplishments (for Daily)
  if (
    type === "Daily" &&
    report.accomplishments &&
    Array.isArray(report.accomplishments)
  ) {
    doc.setFontSize(14);
    doc.text("Today's Accomplishments:", 20, currentY);
    currentY += 8;
    doc.setFontSize(11);
    report.accomplishments.forEach((task: any) => {
      doc.text(`• ${task.title || task}`, 25, currentY);
      currentY += 7;
    });
    currentY += 5;
  }

  // Content
  doc.setFontSize(14);
  doc.text("Summary / Comments:", 20, currentY);
  currentY += 7;
  doc.setFontSize(11);
  const splitText = doc.splitTextToSize(
    report.userComment || report.summary || "No comments provided.",
    170,
  );
  doc.text(splitText, 20, currentY);
  currentY += splitText.length * 7 + 10;

  // Signatures
  let y = Math.max(currentY, 180);
  doc.line(20, y, 190, y);
  y += 10;

  doc.text("Employee Signature:", 20, y);
  if (report.signatureUrl && report.signatureUrl.startsWith("data:image")) {
    doc.addImage(report.signatureUrl, "PNG", 20, y + 2, 40, 20);
  } else if (report.signatureUrl) {
    doc.text("SIGNED (Digital)", 20, y + 10);
  }

  // Supervisor
  doc.text("Supervisor:", 65, y);
  if (
    report.supervisorSignatureUrl &&
    report.supervisorSignatureUrl.startsWith("data:image")
  ) {
    doc.addImage(report.supervisorSignatureUrl, "PNG", 65, y + 2, 40, 20);
  } else if (report.supervisorSignatureUrl) {
    doc.text("APPROVED", 65, y + 10);
  }
  if (report.supervisorComment) {
    doc.setFontSize(8);
    doc.text(`"${report.supervisorComment}"`, 65, y + 25, { maxWidth: 40 });
    doc.setFontSize(11);
  }

  // HoD
  doc.text("HoD:", 110, y);
  if (
    report.headSignatureUrl &&
    report.headSignatureUrl.startsWith("data:image")
  ) {
    doc.addImage(report.headSignatureUrl, "PNG", 110, y + 2, 40, 20);
  } else if (report.headSignatureUrl) {
    doc.text("APPROVED", 110, y + 10);
  }
  if (report.headComment) {
    doc.setFontSize(8);
    doc.text(`"${report.headComment}"`, 110, y + 25, { maxWidth: 40 });
    doc.setFontSize(11);
  }

  // Manager
  doc.text("Manager:", 155, y);
  if (
    report.managerSignatureUrl &&
    report.managerSignatureUrl.startsWith("data:image")
  ) {
    doc.addImage(report.managerSignatureUrl, "PNG", 155, y + 2, 40, 20);
  } else if (report.managerSignatureUrl) {
    doc.text("APPROVED", 155, y + 10);
  }
  if (report.managerComment) {
    doc.setFontSize(8);
    doc.text(`"${report.managerComment}"`, 155, y + 25, { maxWidth: 40 });
    doc.setFontSize(11);
  }

  // Footer
  doc.setFontSize(10);
  doc.text("Generated by Office Management System", 105, 285, {
    align: "center",
  });

  doc.save(
    `${type}_Report_${report.date || report.startDate || report.month}_${user.lastName}.pdf`,
  );
}
